### ISSUE TITLE
Missing asterisk in on of lews therins messages

### ISSUE THREAD

**Issue by ZakariaTalhami** [Tobuss/Lews-Therin-Bot#2]
I noticed on one of the posts, that one of his quotes had a asterisk, there seems to be a missing asterisk at the end of this line.
https://github.com/Tobuss/Lews-Therin-Bot/blob/4df3ab79a24cc10482014e45f1958b985dd73ffb/lews.txt#L30

**Comment by Tobuss** [comment]
Thanks for picking up on this! issues resolved now!

**Comment by ZakariaTalhami** [comment]
No problem, I love the bot.
